### ISSUE TITLE
Script appears to be failing to find the following element

### ISSUE THREAD

**Issue by gustininho** [rileypeterson/Depop#11]
![Screenshot from 2019-09-28 18-34-47](https://user-images.githubusercontent.com/34207069/65818894-b0865280-e21e-11e9-9288-16a3c3e14ffb.png)

The script was working until today. But once I've tried to use it today I faced the same error all the time.

**Comment by gustininho** [comment]
@rileypeterson  I could provide you with a Depop account

**Comment by rileypeterson** [comment]
I just looked at this. Still seems like a bit of mystery to me. Just tried to fix it. Let me know if the newest version works or not.

If not lets get in touch privately because having an account would help me debug this.

**Comment by gustininho** [comment]
![Screenshot from 2019-10-03 19-05-46](https://user-images.githubusercontent.com/34207069/66144088-e0639a80-e610-11e9-903c-5fd48759c275.png)

Yeah, now it finds the element, but fails to find button.

I have sent the account user and pass via email to rileypeterson21@gmail.com 
@rileypeterson

**Comment by rileypeterson** [comment]
Still not working?

**Comment by gustininho** [comment]
Yes, as in the newest Issue reported I have the same problem with following mode.

**Comment by rileypeterson** [comment]
https://github.com/rileypeterson/Depop#status
