### ISSUE TITLE
After I select mode, the script stops with no error message

### ISSUE THREAD

**Issue by RachelDuffin** [rileypeterson/Depop#6]
Hi! I'm running the script on ubuntu, and have no problem up to where I input "following". After that, the script just seems to end and doesn't give me a prompt to select the name of a user. Might you have any idea why this might be or if I could be doing something wrong? Thanks!

**Comment by rileypeterson** [comment]
Does the browser go to your user profile? [That should be the next thing to happen](https://github.com/rileypeterson/Depop/blob/master/depop_github.py#L15-L18).

**Comment by RachelDuffin** [comment]
It goes to my profile and logs me in, and then after that I input "following" but then it just stops and I get an "errno 111 connection refused" error and it stops.

**Comment by rileypeterson** [comment]
Could you post the full traceback?

**Comment by gustininho** [comment]
![image](https://user-images.githubusercontent.com/34207069/54645744-93b9d700-4aa5-11e9-9f2b-14a3c39fd834.png)

I do not get any traceback, The program works but it does nothing. It only clicks on my followers and that is it. I believe that we experience the same issue. Please help!

**Comment by Deorbiting** [comment]
Having the exact same problem and it is the same with unfollowing. :/
