### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by wulfixyt** [rileypeterson/Depop#8]
Hey Riley, 
I appreciate your post a lot but I can get it to work. I downloaded the Depop-Bugfix2019 but when I run it theres a problem with "FileNotFoundError", may you help me?

Traceback (most recent call last):
  File "C:/Users/nicol/Downloads/Depop-bugfix2019/depop.py", line 30, in <module>
    except FileNotFoundError:
NameError: name 'FileNotFoundError' is not defined

**Comment by rileypeterson** [comment]
@wulfixyt

This seems like you might be using Python 2 as the FileNotFoundError was introduced in Python 3. You should be using Python 3.

You can check you're version with `python --version`

Sometimes on operating systems where you have both python 2 and 3, the alias for python 3 is `python3`

**Comment by wulfixyt** [comment]
Thanks a lot.
Had problems because I also had installed Python 2.7 but did only install Selenium for it and not for 3,7.
